baseurl = "http://openxtra.org/"
title = "OPENXTRA Freestuff"
theme = "hugo-bootstrap-premium"
languageCode = "en-us"
defaultContentLanguage = "en"
googleAnalytics = ""

paginate = 10

[menu]

# Main navigation menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url  = "/project/"
    weight = 2

[[menu.main]]
    name = "Articles"
    url  = "/article/"
    weight = 3

[params]

    copyright = "Copyright (&copy;) 2003 - 2017, OPENXTRA Limited. All rights reserved."
    style = "default"
   
    date_format = "2006-01-02"
    